# LSTM 소개
- 코랩에서 실행해야 함
- 기본 LSTM
- Stacked LSTM
- Bidirectional LSTM


In [1]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

## 시계열 데이터를 테이블 구조로 바꾸는 함수
- n_steps: LSTM 모델이 과거 몇개의 입력을 고려할지를 지정

In [2]:
def split_sequence(sequence, n_steps):
  X, y = [],[]
  for i in range(len(sequence)):
    end_ix = i + n_steps
    if end_ix > len(sequence)-1:
      break
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

- 시계열 데이터를 테이블 구조로 바꾸는 예
- 간단한 데이터로 LSTM 모델을 만드는 방법을 설명하겠다

In [3]:
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
n_steps = 3
X, y = split_sequence(raw_seq, n_steps)
X, y

(array([[10, 20, 30],
        [20, 30, 40],
        [30, 40, 50],
        [40, 50, 60],
        [50, 60, 70],
        [60, 70, 80]]), array([40, 50, 60, 70, 80, 90]))

### LSTM 모델은 [samples, timesteps, features] 구조의 입력을 사용
- 2차원이 아니라, 3차원 구조의 데이터가 필요하다

- samples: 샘플수
- timesteps: n_steps를 말함
- features: 한 입력의 특성수

In [4]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
X

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])


## 기본 LSTM

In [5]:
model = Sequential()
model.add(LSTM(20, activation='relu', input_shape=(n_steps, n_features))) 
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=200, verbose=0)

x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[102.36681]]


In [6]:
x_input

array([[[70],
        [80],
        [90]]])

In [7]:
# 샘플 입력 예
x_input = array([700, 800, 900])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[1000.0344]]


## Stacked LSTM

- LSTM을 2개의 레이어로 구성하는 경우
- 첫번째 레이어에서 return_sequences=True 옵션을 지정해야 한다

In [8]:
model = Sequential()
model.add(LSTM(20, activation='relu', return_sequences=True, 
               input_shape=(n_steps, n_features)))
model.add(LSTM(20, activation='relu')) 
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=200, verbose=0)
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0) 
print(yhat)

[[102.854485]]


## Bidirectional LSTM
- 양방향으로 학습한다


In [9]:
from keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(20, activation='relu'), 
                        input_shape=(n_steps, n_features))) 
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=200, verbose=0)
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[101.38728]]
